travis:
  secure:
    BINSTAR_TOKEN: MRDJq0oieneLSr+21/9IIF2qjDJ/1VIkwaqsIJOdUG2ZD7y5RVD4WdcSAuTJVaSq6qrek6jRcvqeMf79y1QcIztX3sgt3/++SNT/kM+45RWi52/xRn8PyA91993+69u9IYpd903/MjcDLb9iFMsrYgdsh4EqpCH34ZlmTHEmqNEOc1S9YGtN4qpEUKQuKCHtPwgv5CTWK6BEbDFq7SL9IsyZvvlT5ZpUAn9YHBa3B98U5AKTyOG64Y7kCi7F79tQKGJZmQhYQwrWTkMpP2yNdR85gIRZauYbHLc0GXoh6bNC2bqsn3TaukCjWppB/FXu2VbZUgXbO3iQf6Q/WQJmBw7OjG5bfAc7kKOsIVK/1laW1MUMFRH7i37P/muPa100w7gb4EKe1KTYvDvNUcIABscwAyri/t5A/bGLWX4opTPuKdRgMxHCpg/corafxQjZdOMRlze+eFSRLa98K/WUIWwV3SjF+cYgDUmO4JOCBQsP4adf4NKy3hyhUR7kZkHj15ytEI75w+CoCpgRwL49kvh6YLEerp9cTz7A18T6SxGH7PfuNyVEV80FuyeenWWy01P/CaeNT7w5cXkkUuNPzLCuG20mc1dl3h6TnUo+T0ou04rPznTPyMzaVxvMwNk1eClhpy/wzL48tWuYH/GHRi8NVPS4h8L4YIgobasQFd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
